### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by petschki** [collective/collective.recipe.rsync#7]
I've added a mini Python 3 fix to this super usefull tool. Can we have a release of that?

/cc @aclark4life

**Comment by aclark4life** [comment]
@petschki Thanks! Are you petschki on PyPI?

**Comment by petschki** [comment]
yes 👍

**Comment by gforcada** [comment]
@aclark4life @petschki  there are `plone` and `collective` users as well, to avoid the bus factor any other time later on

**Comment by aclark4life** [comment]
@petschki @gforcada Thanks, added @collective and @petschki petschki as Owner, Maintainer respectively.

<img width="1233" alt="Screenshot 2019-03-21 08 04 02" src="https://user-images.githubusercontent.com/72164/54751018-04e5b100-4bb0-11e9-8fcb-3e54b1fab7b3.png">

**Comment by petschki** [comment]
thanks! released 2.3.0
